name: AI Architect Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  mlops-and-testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Configurar Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Fase 1 - Entrenar Modelo
      run: python model/train.py
      
    - name: Fase 2 - Evaluar Métricas (MLOps)
      run: python model/evaluate.py
      
    - name: Fase 3 - Pruebas Unitarias de Software
      run: pytest tests/